apiVersion: v1
kind: Service
metadata: 
  name: frontend
spec: 
  type: LoadBalancer
  selector: 
    app: frontend
  ports: 
  - port: 80
    targetPort: 80
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: duypk2000/capstone-frontend:v1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  minReadySeconds: 10
